CREATE DATABASE IF NOT EXISTS userdb_salon;
CREATE DATABASE IF NOT EXISTS bookingdb_salon;
CREATE DATABASE IF NOT EXISTS categorydb_salon;
CREATE DATABASE IF NOT EXISTS paymentdb_salon;
CREATE DATABASE IF NOT EXISTS salondb_salon;
CREATE DATABASE IF NOT EXISTS servicesdb_salon;
CREATE DATABASE IF NOT EXISTS notificationdb_salon;
CREATE DATABASE IF NOT EXISTS reviewdb_salon;